import type { Metadata } from 'next'
import { Inter, Lobster } from 'next/font/google'
import { twMerge } from 'tailwind-merge'
import './globals.css'
const primary = Inter({ subsets: ['latin'], variable: '--primary' })

const secondary = Lobster({
  subsets: ['latin'],
  variable: '--secondary',
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          primary.variable,
          secondary.variable,
          ' antialiased bg-gray-900 text-white font-primary'
        )}
      >
        {children}
      </body>
    </html>
  )
}
